### ISSUE TITLE
Use a Modular CSS Methodology for all custom CSS (e.g. BEM, SMACSS)

### ISSUE THREAD

**Issue by adamdawkins** [SpaceTalk/SpaceTalk#82]
I think CSS is probably more different between personal developers than any other language; so we could do with some stricter guidelines on custom styling. Especially when it comes to the _maintainability_ of the CSS going forwards.

Any rules are better than no rules to some extent, but I'd suggest we use [BEM](https://css-tricks.com/bem-101/):
- It's got clearly defined rules
- All rules are on classes so specificity stays under control
- It plays great with SCSS
- Developers could write classes to perform actions without needing to look them up in the CSS.

e.g. We currently have this.

``` html
  <aside class="channel-info channel-info-out">
    <span class="title">
      Channel info
      <i data-action="display-channel-info" class="fa fa-times channel-info-exit"></i>
    </span>
    <div class="aside-section channel-accordion">
      <ul class="scroll">
        <li>
          <input type="checkbox" checked>
          <i class="fa fa-caret-down"></i>
          <h2><i class="fa fa-info-circle icon icon-about"></i> About this channel</h2>
          <p>About this channel to be here</p>
        </li>
        <li>
          <input type="checkbox" checked>
          <i class="fa fa-caret-down"></i>
          <h2><i class="fa fa-thumb-tack icon icon-pinned"></i> Pinned items</h2>
          <p>Pinned items content to be here</p>
        </li>
        <li>
          <input type="checkbox" checked>
          <i class="fa fa-caret-down"></i>
          <h2><i class="fa fa-user icon icon-members"></i> Members</h2>
          <p>Members content to be here</p>
        </li>
      </ul>
    </div>
  </aside>
```

Combined with a lot of styling based on element names, or nested styles. I'll point out some of the potential problem areas.

(I should point out, this is actually a nice pure-CSS solution for the info panel written by @nabiltntn, it's just the naming conventions and scalability that may need addressing).

``` scss
.channel-info .title {} // .title could be used elsewhere, so this may not do what is expected
.channel-info .channel-accordion ul li {} // I actually tried to add another ul here for other reasons, heavily affected by this CSS

/* we're restricted to using a p element here */
.channel-info .channel-accordion {
 ul li input[type=checkbox]:checked ~ p {
       margin-top: 0;
       max-height: 0;
       opacity: 0;
      transform: translate(0, 50%);
     }
}
```

In BEM, we'd have something more like this:

``` html
  <aside class="channel-info channel-info--out">
    <span class="channel-info__title">
      Channel info
      <i data-action="display-channel-info" class="fa fa-times channel-info-exit"></i>
    </span>
    <div class="channel-info__section channel-accordion">
      <ul class="scroll">
        <li class="channel-accordion__list-item">
          <input type="checkbox" checked>
          <i class="fa fa-caret-down"></i>
          <h2><i class="fa fa-info-circle icon icon-about"></i> About this channel</h2>
          <p class="channel-accordion__list-item-content">About this channel to be here</p>
        </li>
      </ul>
    </div>
  </aside>
```

and the classes used here make the CSS become markup agnostic.

``` scss
// Blocks
.channel-info {}
.channel-accordion {}

// elements
.channel-info__title {}
.channel-info__section {}

.channel-accordion__list-item {}
.channel-accordion__list-item-content {}

// modifiers (or 'states')
.channel-info--out {}
.channel-footer--full {}
.channel-content--full {}
```

Lastly, using a pre-defined method would give us a great reference point to pass on to people trying to skin their own version; add new features; submit changes, etc.
